class MyException(Exception):
    pass;

try:
    raise MyException;
except:
    print("ss");

